### ISSUE TITLE
run current matlab script doesn't work because double qoutes

### ISSUE THREAD

**Issue by shenhai-ran** [apommel/vscode-matlab-interactive-terminal#22]
Hi,

I used the command `run current matlab script` after the interactive terminal is activated.
I got the this error:

`Error: Creating a string using double quotes is not supported.  Use the string function.`

I am using Matlab 2016B and Python 3.5

Interestingly though, if I use the command before I initialize the interactive terminal, it works...

Regards,

**Comment by apommel** [comment]
This seems to be a Matlab error, not directly linked with the extension. From my research, you can only initialize string with double quotes in R2017a. What happens when launching your script from Matlab?
When the terminal window is not initialized, the scripts are launched with a slightly different instruction through Python (eng.run vs eng.eval(run ...). But the difference in behavior should be considered as a bug from the API. I can only advise you to update Matlab if it's possible for you or correct your script.

**Comment by shenhai-ran** [comment]
Hi,

Thanks for your help. You are right, Matlab 2019b works fine with double quotes for a string path.
It was the problem with 2016b...
